server:
  port: 0
spring:
  application:
    name: cards-service-uat
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost
