server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost

build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371
