server:
  port: 8071

spring:
  application:
    name: "configserver"

  cloud:
    config:
      server:
        git:
          uri: https://github.com/sivaduduku/springboot-cloud-configuration
          search-paths:
            - 'service-config/*service'
          #username: root
          #passphrase: 12345
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true